/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            type: 'fit'
                        },
                        title: 'Featured',
                        iconCls: 'star',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                itemId: 'homeToolbar',
                                ui: 'light',
                                layout: {
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'segmentedbutton',
                                        id: 'homeToggleButtons',
                                        itemId: '',
                                        ui: 'light',
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'whatsHotButton',
                                                ui: 'action',
                                                text: 'What\'s Hot',
                                                pressed: true
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'tweetsButton',
                                                ui: 'action',
                                                text: 'BAT Tweets'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                html: 'switcher',
                                id: 'homeSwitcher',
                                layout: {
                                    type: 'card'
                                },
                                items: [
                                    {
                                        xtype: 'container',
                                        cls: [
                                            'solidBorder'
                                        ],
                                        html: '',
                                        id: 'home',
                                        autoDestroy: false,
                                        layout: {
                                            type: 'vbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'carousel',
                                                id: 'newsCarousel',
                                                styleHtmlContent: true,
                                                autoDestroy: false,
                                                flex: 1
                                            },
                                            {
                                                xtype: 'container',
                                                html: '',
                                                id: 'featuredAppsContainer',
                                                itemId: 'mycontainer4',
                                                layout: {
                                                    type: 'fit'
                                                },
                                                flex: 1
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        html: 'BAT Tweets',
                                        id: 'tweets'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'card'
                        },
                        title: 'All Apps',
                        iconCls: 'download',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: 'All'
                            },
                            {
                                xtype: 'list',
                                styleHtmlContent: true,
                                itemTpl: [
                                    '<div><div class="bat_appstore_app_icon"><img src="{AppIcon}"></div><h2>{Title}</h2><p>{Description}<br/>{Link}</p></div>'
                                ],
                                store: 'appsByAlpha',
                                grouped: true,
                                indexBar: true
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'My Apps',
                        iconCls: 'user',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: 'My Apps'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Contact Us',
                        iconCls: 'compose',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: 'Contact Us',
                                items: [
                                    {
                                        xtype: 'button',
                                        ui: 'action',
                                        iconCls: 'more',
                                        iconMask: true,
                                        text: '',
                                        align: 'right'
                                    }
                                ]
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    ui: 'light'
                }
            }
        ]
    }

});